# Generated by Django 3.2.12 on 2022-04-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='document',
            new_name='Tbldocument',
        ),
    ]
