# Generated by Django 3.2.12 on 2022-04-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_remove_tbldocument_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbldocument',
            name='document',
        ),
        migrations.AddField(
            model_name='tbldocument',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
