# Generated by Django 3.2.12 on 2022-04-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0005_auto_20220425_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldocument',
            name='document',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
