# Generated by Django 3.2.12 on 2022-04-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0006_tbldocument_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbldocument',
            old_name='document',
            new_name='doc',
        ),
    ]
