# Generated by Django 3.2.12 on 2022-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0008_rename_doc_tbldocument_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldocument',
            name='filename',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
