# Generated by Django 3.2.12 on 2022-04-26 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0009_alter_tbldocument_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblaccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.CharField(blank=True, max_length=50, null=True)),
                ('end_time', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created_By_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
