# Generated by Django 3.2.12 on 2022-04-26 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0010_tblaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblaccess',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='tblaccess',
            name='start_time',
        ),
    ]
