# Generated by Django 3.2.12 on 2022-04-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0011_auto_20220426_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblaccess',
            name='end_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tblaccess',
            name='start_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
