# Generated by Django 3.2.12 on 2022-04-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0012_auto_20220426_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldocument',
            name='encription_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
