# Generated by Django 3.2.12 on 2022-04-28 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0013_tbldocument_encription_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbldocrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_request', models.IntegerField(default=0)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created_By_req', to='ERP.tbldocument')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created_By_req', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
