# Generated by Django 3.2.12 on 2022-04-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0014_tbldocrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldocrequest',
            name='doc_response',
            field=models.IntegerField(default=0),
        ),
    ]
